### ISSUE TITLE
"amanda kanye" command is missing

### ISSUE THREAD

**Issue by footvaalvica** [marineve17/marcos#3]
I suggest having a command that displays random pictures from the r/WestSubEver subreddit. It has a lot of very funny Kanye memes that I think everyone would love. Please include this in the bot! Thank you. 😄

**Comment by footvaalvica** [comment]
Like this one for example!
![q5y21s0pc7p61](https://user-images.githubusercontent.com/11351574/112676416-504a8e00-8e60-11eb-953a-c60d9b9fa30f.jpg)

**Comment by marineve17** [comment]
I apologise for this inconvenience. It is now fixed. Please do not sue me.
